// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig, env } from "prisma/config";

// Single source of truth for local env vars is .env.local (matches Next.js's own loading order).
config({ path: ".env.local" });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // Migrations always go through the direct (non-pooled) connection — Supabase's
  // pgbouncer pooler doesn't support the session-level features migrations need.
  // The running app (lib/prisma.ts) uses DATABASE_URL instead.
  datasource: {
    url: env("DIRECT_URL"),
  },
});
